# Generated by Django 3.1.4 on 2020-12-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hood',
        ),
    ]
